version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-lpkni-project
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lpkni-project
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:  
  mysql_data:
